name: Daily Investment AI Bot

on:
  schedule:
    - cron: '30 12 * * 1-5'  # Runs 8:30 AM EST (12:30 UTC), Mon–Fri
  workflow_dispatch:

jobs:
  run-daily-investment-bot:
    runs-on: ubuntu-latest

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py (daily picks)
        run: python main.py

      - name: Run followup.py (1-week & 1-month check)
        run: python followup.py

      - name: Run summary.py (Fridays only)
        if: startsWith(github.event.schedule, '30 12') && contains('5', format('{0}', github.event.schedule))
        run: python summary.py
